- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Start point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: true
  last_modified: '2019-06-24 07:19:52.482457'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: Start
  color: pink
  shape: circle
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  push_to_git: false
  device_query_property: ip_address
  scoped_name: Start
  send_notification: false
  send_notification_method: mail
  time_between_retries: 10
  shared: true
  type: swiss_army_knife_service
  vendor: ''
  waiting_time: 0
  device_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: End point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: true
  last_modified: '2019-06-24 07:19:52.491375'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: End
  color: 'pink'
  shared: true
  shape: 'circle'
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  push_to_git: false
  device_query_property: ip_address
  scoped_name: End
  send_notification: false
  send_notification_method: mail
  time_between_retries: 10
  type: swiss_army_knife_service
  vendor: ''
  waiting_time: 0
  device_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Monitor eNMS cluster
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 07:19:52.522003'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: cluster_monitoring
  scoped_name: cluster_monitoring
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  device_query_property: ip_address
  send_notification: false
  send_notification_method: mail
  time_between_retries: 10
  type: swiss_army_knife_service
  vendor: ''
  waiting_time: 0
  device_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Push configurations to Gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 07:19:52.529269'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: git_push_configurations
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple
    - 0
    - 300
  push_to_git: false
  device_query_property: ip_address
  scoped_name: git_push_configurations
  send_notification: false
  send_notification_method: mail
  time_between_retries: 10
  type: swiss_army_knife_service
  vendor: ''
  waiting_time: 0
  device_query: ''